version: '3.8'

services:
  postgresdb:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=todo
    ports:
      - 5432:5432
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - database_data:/var/lib/postgresql/data
  app:
    depends_on:
      - postgresdb
    build: .
    restart: unless-stopped
    ports:
      - 8080:3000
    command: npm run dev
    environment:
      - DB_HOST=postgresdb
      - DB_USER=admin
      - DB_PASSWORD=root
      - DB_NAME=todo
      - DB_PORT=5432
    volumes:
      - .:/app
    stdin_open: true
    tty: true

volumes:
  database_data:
    driver: local